parameters:
    ############################################################################
    # DEFAULTS FOR RUNTIME CONFIGURATION
    ############################################################################

    env(HAL_ROOT): '.'

    env(HAL_ORM_CACHE): 'memory'
    env(HAL_ORM_DEVMODE_ON): '0'
    env(HAL_ORM_PROXY_DIR): '%env(HAL_ROOT)%/.doctrine'
    env(HAL_ORM_CONFIG_DIR): '%env(HAL_ROOT)%/config/doctrine'

    ############################################################################
    # RUNTIME CONFIGURATION
    ############################################################################

    doctrine.config.dev_mode: '%env(HAL_ORM_DEVMODE_ON)%'
    doctrine.path.proxy: '%env(HAL_ORM_PROXY_DIR)%'
    doctrine.path.config: '%env(HAL_ORM_CONFIG_DIR)%'

    doctrine.cache.type: '%env(HAL_ORM_CACHE)%'

    doctrine.connection:
        user:       '%env(HAL_DB_USER)%'
        password:   '%env(HAL_DB_PASSWORD)%'
        host:       '%env(HAL_DB_HOST)%'
        port:       '%env(HAL_DB_PORT)%'
        dbname:     '%env(HAL_DB_NAME)%'
        driver:     '%env(HAL_DB_DRIVER)%'

    ############################################################################
    # STATIC CONFIGURATION
    ############################################################################

    doctrine.cache.lvl2_enabled: true
    doctrine.cache.lvl2_ttl: 600
    doctrine.cache.lvl2_lock: 60

    doctrine.cache.ttl: 600

    doctrine.config.namespace: 'Hal\Core\Entity'
    doctrine.config.namespace_config_map:
        '%doctrine.path.config%': '%doctrine.config.namespace%'

    doctrine.config.custom_types:
        - 'Hal\Core\Type\CompressedJSONArrayType'
        - 'Hal\Core\Type\TimePointType'

    doctrine.proxy.connection:
        driver: 'pdo_sqlite'
        memory: true

services:

    ############################################################################
    # DOCTRINE PROXY
    ############################################################################

    doctrine.em.proxy:
        public: true
        class: 'Doctrine\ORM\EntityManager'
        factory: ['Doctrine\ORM\EntityManager', 'create']
        arguments:
            - '%doctrine.proxy.connection%'
            - '@doctrine.em.proxy.config'
            - '@doctrine.em.event_manager'
        configurator: ['@doctrine.em.configurator', 'configure']

    doctrine.em.proxy.config:
        class: 'Doctrine\ORM\Configuration'
        factory: ['Doctrine\ORM\Tools\Setup', 'createConfiguration']
        arguments:
            - '%doctrine.config.dev_mode%'
            - '%doctrine.path.proxy%'
        calls:
            - ['setMetadataDriverImpl', ['@doctrine.config.driver']]

    ############################################################################
    # DOCTRINE EM
    ############################################################################

    doctrine.em:
        class: 'Doctrine\ORM\EntityManager'
        factory: ['Doctrine\ORM\EntityManager', 'create']
        arguments:
            - '%doctrine.connection%'
            - '@doctrine.config'
            - '@doctrine.em.event_manager'
        configurator: ['@doctrine.em.configurator', 'configure']

    doctrine.em.configurator:
        class: 'Hal\Core\Database\DoctrineUtility\DoctrineConfigurator'
        arguments: ['%doctrine.config.custom_types%']

    doctrine.em.event_manager:
        class: 'Doctrine\Common\EventManager'

    ############################################################################
    # DOCTRINE CONFIG
    ############################################################################

    doctrine.config:
        class: 'Doctrine\ORM\Configuration'
        factory: ['Doctrine\ORM\Tools\Setup', 'createConfiguration']
        arguments:
            - '%doctrine.config.dev_mode%'
            - '%doctrine.path.proxy%'
            - '@doctrine.cache'
        calls:
            - ['setMetadataDriverImpl', ['@doctrine.config.driver']]
            - ['setSecondLevelCacheEnabled', ['%doctrine.cache.lvl2_enabled%']]
            - ['setSecondLevelCacheConfiguration', ['@doctrine.cache.lvl2.config']]

    doctrine.config.driver:
        class: 'Doctrine\ORM\Mapping\Driver\YamlDriver'
        arguments: ['@doctrine.config.driver.file_locator', '.orm.yaml']
        calls:
            - ['setGlobalBasename', ['global']]

    doctrine.config.driver.file_locator:
        class: 'Doctrine\Common\Persistence\Mapping\Driver\SymfonyFileLocator'
        arguments:
            - '%doctrine.config.namespace_config_map%'
            - '.orm.yaml'
            - '/'

    ############################################################################
    # LISTENERS
    ############################################################################

    doctrine.clock:
        class: 'QL\MCP\Common\Time\Clock'
        arguments: ['now', 'UTC']

    ############################################################################
    # DOCTRINE CACHE
    ############################################################################

    doctrine.cache:
        class: 'Doctrine\Common\Cache\Cache'
        factory: ['@service_container', 'get']
        arguments: ['doctrine.cache.%doctrine.cache.type%']

    doctrine.cache.memory:
        class: 'Doctrine\Common\Cache\ArrayCache'

    # second level cache
    doctrine.cache.lvl2.config:
        class: 'Doctrine\ORM\Cache\CacheConfiguration'
        calls:
            - ['setCacheFactory', ['@doctrine.cache.lvl2.factory']]

    doctrine.cache.lvl2.factory:
        class: 'Doctrine\ORM\Cache\DefaultCacheFactory'
        arguments: ['@doctrine.cache.lvl2.region_config', '@doctrine.cache']

    doctrine.cache.lvl2.region_config:
        class: 'Doctrine\ORM\Cache\RegionsConfiguration'
        arguments:
            - '%doctrine.cache.lvl2_ttl%'
            - '%doctrine.cache.lvl2_lock%'

    ############################################################################
    # DOCTRINE HELPERS
    ############################################################################

    doctrine.random:
        class: 'Hal\Core\RandomGenerator'
