'Hal\Core\Entity\System\UserIdentityProvider':
    table: 'system_identity_providers'
    repositoryClass: 'Hal\Core\Repository\System\UserIdentityProviderRepository'
    type: 'entity'

    cache: { usage : NONSTRICT_READ_WRITE }

    id:
        id:
            column: 'id'
            type: 'guid'

    fields:

        name:
            column: 'name'
            type: 'string'
            length: 100

        type:
            column: 'provider_type'
            type: 'string'
            length: 50
            options: { default: 'internal' } # See IdentityProviderEnum for list of options

        isOAuth:
            column: 'is_oauth'
            type: 'boolean'
            options: { default: false }

        parameters:
            column: 'parameters'
            type: 'json_array'

        created:
            column: 'created'
            type: 'timepoint'
