'Hal\Core\Entity\User':
    table: 'users'
    repositoryClass: 'Hal\Core\Repository\UserRepository'
    type: 'entity'

    cache: { usage : NONSTRICT_READ_WRITE }

    id:
        id:
            column: 'id'
            type: 'guid'

    fields:

        name:
            column: 'name'
            type: 'string'
            length: 100

        settings:
            column: 'settings'
            type: 'json_array'

        isDisabled:
            column: 'is_disabled'
            type: 'boolean'
            options: { default: false }

        created:
            column: 'created'
            type: 'timepoint'

    oneToMany:

        tokens:
            targetEntity: 'Hal\Core\Entity\User\UserToken'
            mappedBy: 'user'

        identities:
            targetEntity: 'Hal\Core\Entity\User\UserIdentity'
            mappedBy: 'user'

